//
// CompositeFairing.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Model for CompositeFairing */

internal struct CompositeFairing: Codable {

    internal var diameter: Diameter
    internal var height: Height?

    internal init(diameter: Diameter, height: Height?) {
        self.diameter = diameter
        self.height = height
    }


}

