//
// Engines.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Model for Engines */

internal struct Engines: Codable {

    internal var engineLossMax: Int?
    internal var isp: Isp?
    internal var layout: String?
    internal var number: Int?
    internal var propellant1: String?
    internal var propellant2: String?
    internal var thrustSeaLevel: ThrustSeaLevel?
    internal var thrustToWeight: Float?
    internal var thrustVacuum: ThrustVacuum?
    internal var type: String?
    internal var version: String?

    internal init(engineLossMax: Int?, isp: Isp?, layout: String?, number: Int?, propellant1: String?, propellant2: String?, thrustSeaLevel: ThrustSeaLevel?, thrustToWeight: Float?, thrustVacuum: ThrustVacuum?, type: String?, version: String?) {
        self.engineLossMax = engineLossMax
        self.isp = isp
        self.layout = layout
        self.number = number
        self.propellant1 = propellant1
        self.propellant2 = propellant2
        self.thrustSeaLevel = thrustSeaLevel
        self.thrustToWeight = thrustToWeight
        self.thrustVacuum = thrustVacuum
        self.type = type
        self.version = version
    }

    internal enum CodingKeys: String, CodingKey {
        case engineLossMax = "engine_loss_max"
        case isp
        case layout
        case number
        case propellant1 = "propellant_1"
        case propellant2 = "propellant_2"
        case thrustSeaLevel = "thrust_sea_level"
        case thrustToWeight = "thrust_to_weight"
        case thrustVacuum = "thrust_vacuum"
        case type
        case version
    }


}

