//
// Height.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Model for Height */

internal struct Height: Codable {

    internal var feet: Float?
    internal var meters: Float?

    internal init(feet: Float?, meters: Float?) {
        self.feet = feet
        self.meters = meters
    }


}

