//
// Isp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Model for Isp */

internal struct Isp: Codable {

    internal var seaLevel: Int
    internal var vacuum: Int?

    internal init(seaLevel: Int, vacuum: Int?) {
        self.seaLevel = seaLevel
        self.vacuum = vacuum
    }

    internal enum CodingKeys: String, CodingKey { 
        case seaLevel = "sea_level"
        case vacuum
    }


}

