//
// LandingLegs.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

//import Foundation
//
//
///** Model for LandingLegs */
//
//internal struct LandingLegs: Codable {
//
//    internal var material: String?
//    internal var number: Int?
//
//    internal init(material: String?, number: Int?) {
//        self.material = material
//        self.number = number
//    }
//
//
//}

