//
// Payloads.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Model for Payloads */

internal struct Payloads: Codable {

    internal var compositeFairing: CompositeFairing?
    internal var option1: String?

    internal init(compositeFairing: CompositeFairing?, option1: String?) {
        self.compositeFairing = compositeFairing
        self.option1 = option1
    }

    internal enum CodingKeys: String, CodingKey { 
        case compositeFairing = "composite_fairing"
        case option1 = "option_1"
    }


}

