//
// PayloadWeights.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Model for PayloadWeights */

internal struct PayloadWeights: Codable {

    internal var _id: String?
    internal var kg: Int?
    internal var lb: Int?
    internal var name: String?

    internal init(_id: String?, kg: Int?, lb: Int?, name: String?) {
        self._id = _id
        self.kg = kg
        self.lb = lb
        self.name = name
    }

    internal enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case kg
        case lb
        case name
    }


}

