//
// Rocket.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Model for Rocket */

internal struct Rocket: Codable {

    internal var active: Bool
    internal var boosters: Int?
    internal var company: String?
    internal var costPerLaunch: Int?
    internal var country: String?
    internal var _description: String?
    internal var diameter: Diameter?
    internal var engines: Engines?
    internal var firstFlight: Date?
    internal var firstStage: FirstStage?
    internal var flickrImages: [String]?
    internal var height: Height?
    internal var _id: String?
    internal var landingLegs: LandingLegs?
    internal var mass: Mass?
    internal var name: String?
    internal var payloadWeights: [PayloadWeights]?
    internal var secondStage: SecondStage?
    internal var stages: Int?
    internal var successRatePct: Int?
    internal var type: String?
    internal var wikipedia: String?

    internal init(active: Bool, boosters: Int?, company: String?, costPerLaunch: Int?, country: String?, _description: String?, diameter: Diameter?, engines: Engines?, firstFlight: Date?, firstStage: FirstStage?, flickrImages: [String]?, height: Height?, _id: String?, landingLegs: LandingLegs?, mass: Mass?, name: String?, payloadWeights: [PayloadWeights]?, secondStage: SecondStage?, stages: Int?, successRatePct: Int?, type: String?, wikipedia: String?) {
        self.active = active
        self.boosters = boosters
        self.company = company
        self.costPerLaunch = costPerLaunch
        self.country = country
        self._description = _description
        self.diameter = diameter
        self.engines = engines
        self.firstFlight = firstFlight
        self.firstStage = firstStage
        self.flickrImages = flickrImages
        self.height = height
        self._id = _id
        self.landingLegs = landingLegs
        self.mass = mass
        self.name = name
        self.payloadWeights = payloadWeights
        self.secondStage = secondStage
        self.stages = stages
        self.successRatePct = successRatePct
        self.type = type
        self.wikipedia = wikipedia
    }

    internal enum CodingKeys: String, CodingKey { 
        case active
        case boosters
        case company
        case costPerLaunch = "cost_per_launch"
        case country
        case _description = "description"
        case diameter
        case engines
        case firstFlight = "first_flight"
        case firstStage = "first_stage"
        case flickrImages = "flickr_images"
        case height
        case _id = "id"
        case landingLegs = "landing_legs"
        case mass
        case name
        case payloadWeights = "payload_weights"
        case secondStage = "second_stage"
        case stages
        case successRatePct = "success_rate_pct"
        case type
        case wikipedia
    }


}

